/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package biblo2;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ghofran
 */
public class request extends javax.swing.JFrame {
    Connection con;
    PreparedStatement pst;
    ResultSet rs ;
    /**
     * Creates new form request
     */
    public request() {
        initComponents();
        listlivres_dispo();
        setupTableLivresDispo();
        Listelivres();
        listlivres_emprunt();
        Liste_abonne();
        Listelivres2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ID_em = new javax.swing.JComboBox<>();
        Titre_em = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        Titre_di = new javax.swing.JComboBox<>();
        jButton8 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Livres Disponibles");

        jLabel2.setBackground(new java.awt.Color(0, 0, 153));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Livres Empruntés");

        ID_em.setBackground(new java.awt.Color(204, 204, 255));
        ID_em.setForeground(new java.awt.Color(204, 204, 255));
        ID_em.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_emActionPerformed(evt);
            }
        });

        Titre_em.setBackground(new java.awt.Color(204, 204, 255));
        Titre_em.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Titre_emActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(83, 135, 213));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Rechercher");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Livre ID", "Livre Titre", "Empranteur"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Livre ID", "Livre Titre"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton2.setBackground(new java.awt.Color(83, 135, 213));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Rechercher");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Titre_di.setBackground(new java.awt.Color(204, 204, 255));
        Titre_di.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Titre_diActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(83, 135, 213));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Abonnés");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(83, 135, 213));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Emprunt");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(83, 135, 213));
        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Livres");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Livre_ID", "Livre_Titre", "Empruntur_Nom", "Emprenteur_ID"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ID_em, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Titre_em, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(68, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Titre_di, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(229, 229, 229)
                            .addComponent(jLabel1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Titre_em, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ID_em, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Titre_di, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton6)
                    .addComponent(jButton9))
                .addGap(107, 107, 107))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ID_emActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_emActionPerformed
       
    }//GEN-LAST:event_ID_emActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            
        
      try  {
        
        
        con=DriverManager.getConnection( "jdbc:mysql://localhost:3306/bib","root","");
        String titree = String.valueOf(Titre_em.getSelectedItem());
        String nomabonne = String.valueOf(ID_em.getSelectedItem());
        String sql2 = "SELECT l.idlivre, l.titre, a.nomab FROM abonne a, livre l WHERE l.idabonne = a.idab and (l.titre = ? or a.nomab = ?) ";
        pst = con.prepareStatement(sql2);
        pst.setString(1, titree);
        pst.setString(2, nomabonne);
         ResultSet rs1 = pst.executeQuery();
         DefaultTableModel table2 = (DefaultTableModel) jTable1.getModel();
            table2.setRowCount(0);
             
            while (rs1.next()){
                
                String idlivre1 = String.valueOf(rs1.getInt("idlivre"));
                String titre1 = String.valueOf(rs1.getString("titre"));
                 String nomab1 = String.valueOf(rs1.getString("nomab"));
                String tbData [] = {idlivre1,titre1,nomab1} ;
                
               table2.addRow(tbData);
               
            }
            
        con.close();
        
        /*Class.forName("com.mysql.cj.jdbc.Driver");
        con=DriverManager.getConnection( "jdbc:mysql://localhost:3306/bib","root","");
        String nomabonne = String.valueOf(ID_em.getSelectedItem());
        String sql = "SELECT l.idlivre, l.titre, a.nomab FROM abonne a, livre l WHERE l.idabonne = a.idab and a.nomab = ?  ";
        pst = con.prepareStatement(sql);
        pst.setString(1, nomabonne);
         ResultSet rs = pst.executeQuery();
         DefaultTableModel table1 = (DefaultTableModel) jTable1.getModel();
            table1.setRowCount(0);
            while (rs.next()){
                String idlivre = String.valueOf(rs.getInt("idlivre"));
                String titre = String.valueOf(rs.getString("titre"));
                 String nomab = String.valueOf(rs.getString("nomab"));
                String tbData [] = {idlivre,titre,nomab} ;
                table1.addRow(tbData);
            }
        con.close();*/
        
        
    } catch (Exception e) {
        e.printStackTrace();
    } 
     /* try{
      Class.forName("com.mysql.cj.jdbc.Driver");
        con=DriverManager.getConnection( "jdbc:mysql://localhost:3306/bib","root","");
        String nomabonne = String.valueOf(ID_em.getSelectedItem());
        String sql = "SELECT l.idlivre, l.titre, a.nomab FROM abonne a, livre l WHERE l.idabonne = a.idab and a.nomab = ?  ";
        pst = con.prepareStatement(sql);
        pst.setString(1, nomabonne);
         ResultSet rs = pst.executeQuery();
         DefaultTableModel table1 = (DefaultTableModel) jTable1.getModel();
            table1.setRowCount(0);
            while (rs.next()){
                String idlivre = String.valueOf(rs.getInt("idlivre"));
                String titre = String.valueOf(rs.getString("titre"));
                 String nomab = String.valueOf(rs.getString("nomab"));
                String tbData [] = {idlivre,titre,nomab} ;
                table1.addRow(tbData);
            }
        con.close();
      
      }catch (Exception e) {
        e.printStackTrace();
    }*/
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
    try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bib", "root", "");
    String Titre = String.valueOf(Titre_di.getSelectedItem());
    String sql = "SELECT titre FROM livre WHERE titre=? And disponible=0;";
    pst = con.prepareStatement(sql);
    pst.setString(1, Titre);
    ResultSet rs = pst.executeQuery();
    if (rs.next()) {
        JOptionPane.showMessageDialog(null, "Le livre est DISPONIBLE.");
    } else {
        JOptionPane.showMessageDialog(null, "Le livre n'est pas DISPONIBLE.");
    }
    rs.close();
} catch (Exception e) {
    e.printStackTrace();
}

        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Titre_diActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Titre_diActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Titre_diActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Abonne1 ou = new Abonne1();
        this.setVisible(false);
        ou.setVisible(true) ;
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Emprunts ou = new Emprunts();
        this.setVisible(false);
        ou.setVisible(true) ;
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        livre au = new livre();
        this.setVisible(false);
        au.setVisible(true) ;
    }//GEN-LAST:event_jButton9ActionPerformed

    private void Titre_emActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Titre_emActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Titre_emActionPerformed
  public void listlivres_emprunt (){
            try  {
                Titre_di.removeAllItems();
            Class.forName("com.mysql.cj.jdbc.Driver"); 
            con=DriverManager.getConnection( "jdbc:mysql://localhost:3306/bib","root","");  
            String sql= "select titre from livre ;" ;
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()){
                String Titre = rs.getString("titre");
                Titre_di.addItem(Titre);
            }
            con.close();
        }catch (Exception e) {
            e.printStackTrace();
        }
    
    }
  
      public void Liste_abonne(){
            try{
         ID_em.removeAllItems();
        Class.forName("com.mysql.cj.jdbc.Driver"); 
        con=DriverManager.getConnection( "jdbc:mysql://localhost:3306/bib","root",""); 
        String sql= "select nomab from abonne;" ; 
        pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()){
                String Titre = rs.getString("nomab");
                ID_em.addItem(Titre);
            }
            con.close();
            
            }catch (Exception e) {
            e.printStackTrace();
        }
            
            
        }
      
         public void Listelivres2 () {
                try  {
             Titre_em.removeAllItems();
            Class.forName("com.mysql.cj.jdbc.Driver"); 
            con=DriverManager.getConnection( "jdbc:mysql://localhost:3306/bib","root","");  
            String sql= "select titre from livre ;" ;
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()){
                String Titre = rs.getString("titre");
                Titre_em.addItem(Titre);
            }
            con.close();
            
        }catch (Exception e) {
            e.printStackTrace();
        }
    }
        
              public void Listelivres () {
                try  {
             Titre_di.removeAllItems();
            Class.forName("com.mysql.cj.jdbc.Driver"); 
            con=DriverManager.getConnection( "jdbc:mysql://localhost:3306/bib","root","");  
            String sql= "select titre from livre ;" ;
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()){
                String Titre = rs.getString("titre");
                Titre_di.addItem(Titre);
            }
            con.close();
            
        }catch (Exception e) {
            e.printStackTrace();
        }
    }
              
               
            public void listlivres_dispo (){
            try  {
            Class.forName("com.mysql.cj.jdbc.Driver"); 
            con=DriverManager.getConnection( "jdbc:mysql://localhost:3306/bib","root","");  
            String sql= "select idlivre,titre from livre where disponible = '0'" ;
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
           DefaultTableModel table1 = (DefaultTableModel) jTable2.getModel();
            table1.setRowCount(0);
            while (rs.next()){
               String id_livre = String.valueOf(rs.getInt("idlivre"));
                String Titre = String.valueOf(rs.getString("titre"));
                String tbData [] = {id_livre,Titre};
                table1.addRow(tbData);
            }
            con.close();
        }catch (Exception e) {
            e.printStackTrace();
        }
    
    }

    
 
        
        public void setupTableLivresDispo () {
     try  {
            Class.forName("com.mysql.cj.jdbc.Driver"); 
            con=DriverManager.getConnection( "jdbc:mysql://localhost:3306/bib","root","");  
            String sql= "select l.idlivre,l.titre,l.idabonne,a.nomab from livre l , abonne a where l.idabonne=a.idab and l.disponible = 1" ;
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            DefaultTableModel table1 = (DefaultTableModel) jTable4.getModel();
            table1.setRowCount(0);
            while (rs.next()){
                String id_livre = String.valueOf(rs.getInt("idlivre"));
                String Titre = String.valueOf(rs.getString("titre"));
                String id_abonne = String.valueOf(rs.getInt("idabonne"));
                String nomab = String.valueOf(rs.getString("nomab"));
                String tbData [] = {id_livre,Titre,id_abonne,nomab} ;
                table1.addRow(tbData);    
            }
            con.close();
        }catch (Exception e) {
            e.printStackTrace();
        }
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(request.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(request.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(request.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(request.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new request().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ID_em;
    private javax.swing.JComboBox<String> Titre_di;
    private javax.swing.JComboBox<String> Titre_em;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable4;
    // End of variables declaration//GEN-END:variables
}
